# Site wide configuration

title:            Airway
locale:           China
url:              /EyonJoshua91.github.io/airway
safe: false
plugins: /_plugins

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-swfobject

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
# Site owner
owner:
  name: YuYang (EyonJoshua)
  avatar: bio-photo.jpg
  bio: "A Undergraduate Student @TJU China"
  email: hns20070@163.com	
  disqus-shortname: EyonJoshua
  twitter: 
  facebook: 
  google:
    plus:
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: EyonJoshua91
  stackoverflow:
  linkedin:
  instagram: 
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
swfobject:
  height: 350
  width: 200
  express_install_url: expressInstall.swf
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]